/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_native_test2_Myjni */

#ifndef _Included_com_example_native_test2_Myjni
#define _Included_com_example_native_test2_Myjni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_native_test2_Myjni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_native_1test2_Myjni_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
