/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <jni.h>
#include <jni.h>
/* Header for class com_example_ndk_NativeTest */

#ifndef _Included_com_example_ndk_NativeTest
#define _Included_com_example_ndk_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndk_NativeTest
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeTest_init__
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndk_NativeTest
 * Method:    init
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeTest_init__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_ndk_NativeTest
 * Method:    init
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_ndk_NativeTest_init__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_ndk_NativeTest
 * Method:    update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndk_NativeTest_update
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
